### ISSUE TITLE
PersistDomainEventSubscriber

### ISSUE THREAD

**Issue by matiux** [dddinphp/ddd#18]
Hi,
can you suggest me how can I subscribe PersistDomainEventSubscriber globally on Symfony 3?

For now I have registered this two services:

```
  event.repository:
    class: Messenger\Infrastructure\Application\Notification\DoctrineEventStoreRepository
    factory: ['@doctrine', getRepository]
    arguments: ['Messenger\Domain\Event\StoredEvent']

  event.publisher:
    class: Messenger\Domain\DomainEventPublisher
    factory: ['Messenger\Domain\DomainEventPublisher', instance]
```

but I don't understand how (and where) can I subscribe my subscribers

Thanks
